### ISSUE TITLE
Missing a jQuery UI widget or jQuery plugin 

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/07-trello-clone-Oleg-Lopes#1]
As part of the requirements for this assignment you need to supply a basic implementation of either a) a plugin/widget using the jQuery UI Widget factory or b) the jQuery plugin factory.

Please refer to one of the patterns that are defined and available in this repository:

- https://github.com/jquery-boilerplate/jquery-patterns

Extra note: The plugin doesn't have to be that complex, just toggle some CSS property or manipulate the selector in the DOM somehow, text or similar.

**Comment by Oleg-Lopes** [comment]
Doesn't datepicker/tabs/sortable/dialog counts as any of them?

**Comment by linusblom** [comment]
No, they are all build in widgets in jQuery UI, you need to create one of your own.

**Comment by Oleg-Lopes** [comment]
Added, ready to be reviewed
